.\" Please send any bug reports, improvements, comments, patches, 
.\" etc. to Jeff Backus <jeff.backus@gmail.com>.
.TH "BRD" "1" "28 May 2014" "Jeff Backus"
.SH NAME
brd \- scans directories and files for damage due to decay of medium.
.SH SYNOPSIS
.SS "SCANNING DIRECTORIES:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBscan\fR [\fBscan-options\fR] \fBtarget\fR [\fBtarget ...\fR]

.SS "LISTING DATABASE CONTENTS:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBlist\fR [\fBlist-options\fR] [\fBtarget ...\fR]

.SS "SEARCHING FOR DUPLICATE FILES:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBdupe_files\fR [\fBdupe_files-options\fR]

.SS "SEARCHING FOR DUPLICATE SUBTREES:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBdupe_trees\fR [\fBdupe_trees-options\fR]

.SS "DIFFING TREES:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBdiff\fR [\fBdiff-options\fR] \fBleft-target\fR \fBright-target\fR

.SS "REMOVING ITEMS FROM THE DATABASE:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBrm\fR [\fBrm-options\fR] \fBtarget\fR [\fBtarget ...\fR]

.SS "CHECKING THE DATABASE:"
.PP

\fBbrd\fR [\fBgeneral-options\fR] \fBcheckdb\fR [\fBcheckdb-options\fR]

.SS "general-options"
.PP

 [\fB-h\fR] [\fB--version\fR] [\fB-l,--log [\fIFILENAME\fR]\fR] 
 [\fB-v,--verbose\fR] [\fB-d,--debug\fR] [\fB--db [\fIFILENAME\fR]\fR] 

.SS "scan-options"
.PP

 [\fB-h\fR] [\fB--use-root [\fIROOT_NAME\fR]\fR] 
 [\fB--root-prefix [\fIPREFIX\fR]\fR]\fR] [\fB-p,--prune\fR] 
 [\fB-P,--progress\fR] [\fB--check-only\fR] [\fB--dry-run\fR]
 [\fB-s,--skip-recent\fR] [\fB--expr [\fIDAYS\fR]\fR]

.SS "list-options"
.PP

 [\fB-h\fR] [\fB--use-root [\fIROOT_NAME\fR]\fR] [\fB-m,--minimal\fR]
 [\fB--root-prefix [\fIPREFIX\fR]\fR]\fR] [\fB-e,--expanded\fR] 


.SS "dupe_files-options"
.PP

 [\fB-h\fR] [\fB-o,--output [\fIFILENAME\fB]\fR]

.SS "dupe_trees-options"
.PP

 [\fB-h\fR] [\fB-o,--output [\fIFILENAME\fB]\fR] [\fB--nofilefp\fR]
 [\fB--nofilename\fR] [\fB--nosubdirfp\fR] [\fB--nosubdirname\fR]
 [\fB--nodirname\fR]

.SS "diff-options"
.PP

 [\fB-h\fR] [\fB-o,--output [\fIFILENAME\fB]\fR]
 [\fB--use-root [\fIROOT_NAME\fR]\fR]\fR] [\fB--root-prefix [\fIPREFIX\fR]\fR]

.SS "rm-options"
.PP

 [\fB-h\fR] [\fB--use-root [\fIROOT_NAME\fR]\fR]
 [\fB--root-prefix [\fIPREFIX\fR]\fR]\fR] [\fB--dry-run\fR] 
	
.SS "checkdb-options"
.PP

 [\fB-h\fR] [\fB-P,--progress\fR] [\fB--check-only\fR] [\fB--dry-run\fR]

.SH "DESCRIPTION"
.PP
Bit Rot Detector, or \fBbrd\fR, is a tool to scan a directory tree and check each file
for corruption caused by damage to the physical storage medium or by damage from
malicious programs. Files are fingerprinted using the SHA-1 algorithm. File
fingerprints, sizes, and modification times are stored in a SQLite database.

Multiple unrelated directory trees can be stored in the same database. All
trees are identified by the base directory, or root, as specified on the 
command-line. Note that the following are considered different trees:
    some_dir/
    ./some_dir/

Subtrees can be specified anywhere roots can as long as the full root to subtree
path is specified. However, the subtree must already exist in the database. If
the subtree is not currently in the database, it will be considered to be a
new root. For example, the following will scan some_dir as a new root and add 
all of its children to the database, then scan the subtree some_subtree for
problems and/or changes:
    # Add new root
    brd scan some_dir
    # Scan only part of a root for problems and changes.
    brd scan some_dir/some_subtree

Note: the default behavior for scan is to update the database for any files
that are newer than the database record. Files that have been tampered with will
likely be flagged as updated and not as damaged. To properly check for files
that have been tampered with, run scan with the \fB--check-only\fR option.

Since scanning large trees or trees with large files can take quite a while,
it is possible to exclude files in directories that have recently been checked
via the \fB-s\fR option. How recent is "recent" is controlled by the \fB--expr\fR option and
defaults to 30 days.

The integrity of the database can be checked via the \fBcheckdb\fR subcommand.

In addition to checking files for corruption, brd provides the ability to search
the database for duplicate files and subtrees, as well as diff subtrees.
See the \fBdupe_files\fR, \fBdupe_trees\fR, and \fBdiff\fR subcommands for details.

.SS "GENERAL OPTIONS"
.PP
These options can be used in all the different modes.
.TP
\fB-h, --help\fR
Display the command-line help. When specified after a subcommand name, 
subcommand-specific help will be displayed.
.TP
\fB--version\fR
Displays script version number and quits.
.TP
\fB-l,--log \fIFILENAME\fB\fR
Logs output to the specified file instead of the console.
.TP
\fB-v,--verbose\fR
Enables additional messages to screen and/or log file.
.TP
\fB-d,--debug\fR
Enables debug messages to screen and/or log file.
.TP
\fB--db \fIFILENAME\fB\fR
Specifies the name of the database to use. Defaults to "./brd.db"

.SS "SCANNING OPTIONS"
.PP
The following options are available with the \fBscan\fR subcommand:
.TP
\fB--use-root \fIROOT_NAME\fB\fR
Strips the path information from all targets and uses the specified \fIROOT_NAME\fR
instead, when interacting with the database.
.TP
\fB--root-prefix \fIPREFIX\fB\fR
Appends the specified \fIPREFIX\fR to each target when interacting with the 
database useful for only scanning a subtree as opposed to the entire tree.
.TP
\fB-p,--prune\fR
Removes all records for files and directories that no longer exist. If this
option is not specified, missing files and directories will generate a warning. 
With this option, missing items will be noted only if \fB--verbose\fR is used.
.TP
\fB-P,--progress\fR
Displays a progress indicator.
.TP
\fB--check-only\fR
Behaves like normal, except that no changes are committed to the database.
.TP
\fB--dry-run\fR
This command is a synonym for \fB--check-only\fR.
.TP
\fB-s,--skip-recent\fR
Skips recently scanned directories and their contents. Default cut-off is 30
days. See \fB--expr\fR for how to specify the cut-off.
.TP
\fB--expr \fIDAYS\fB\fR
Scans are considered recent for up to, and including, \fIDAYS\fR days. The
default value is 30 days. See \fB--skip-recent\fR for info on skipping recently
scanned directories and their contents.

.SS "LISTING OPTIONS"
.PP
The following options are available with the \fBlist\fR subcommand:
.TP
\fB--use-root \fIROOT_NAME\fB\fR
Strips the path information from all targets and uses the specified \fIROOT_NAME\fR
instead, when interacting with the database.
.TP
\fB--root-prefix \fIPREFIX\fB\fR
Appends the specified \fIPREFIX\fR to each target when interacting with the 
database useful for only scanning a subtree as opposed to the entire tree.
.TP
\fB-m,--minimal\fR
When displaying information on directory targets, only directory contents are
displayed.
.TP
\fB-e,--expanded\fR
Displays additional information for directory targets.

.SS "DUPLICATE FILES OPTIONS"
.PP
The following options are available with the \fBdupe_files\fR subcommand:
.TP
\fB-o,--output \fIFILENAME\fB\fR
Writes the list of duplicate files to the specified file name. Useful when
\fB--verbose\fR or \fB--debug\fR are used.

.SS "DUPLICATE SUBTREES OPTIONS"
.PP
The following options are available with the \fBdupe_trees\fR subcommand:
.TP
\fB-o,--output \fIFILENAME\fB\fR
Writes the list of duplicate subtrees to the specified file name. Useful when
\fB--verbose\fR or \fB--debug\fR are used.
.TP
\fB--nofilefp\fR
When generating the fingerprint for a directory, do not include  the 
fingerprints of files associated with it.
.TP
\fB--nofilename\fR
When generating the fingerprint for a directory, do not include the file names
of files associated with it.
.TP
\fB--nosubdirfp\fR
When generating the fingerprint for a directory, do not include the fingerprints
of subdirectories.
.TP
\fB--nosubdirname\fR
When generating the fingerprint for a directory, do not include the names of
subdirectories.
.TP
\fB--nodirname\fR
When generating the fingerprint for a directory, do not include the directory's
name.

.SS "DIFF OPTIONS"
.PP
The following options are available with the \fBdiff\fR subcommand:
.TP
\fB-o,--output \fIFILENAME\fB\fR
Writes the results to the specified file name. Useful when
\fB--verbose\fR or \fB--debug\fR are used.
.TP
\fB--use-root \fIROOT_NAME\fB\fR
Strips the path information from all targets and uses the specified \fIROOT_NAME\fR
instead, when interacting with the database.
.TP
\fB--root-prefix \fIPREFIX\fB\fR
Appends the specified \fIPREFIX\fR to each target when interacting with the 
database useful for only scanning a subtree as opposed to the entire tree.

.SS "REMOVAL OPTIONS"
.PP
The following options are available with the \fBrm\fR subcommand:
.TP
\fB--use-root \fIROOT_NAME\fB\fR
Strips the path information from all targets and uses the specified \fIROOT_NAME\fR
instead, when interacting with the database.
.TP
\fB--root-prefix \fIPREFIX\fB\fR
Appends the specified \fIPREFIX\fR to each target when interacting with the 
database useful for only scanning a subtree as opposed to the entire tree.
.TP
\fB--dry-run\fR
Behaves like normal, except that no changes are committed to the database.

.SS "DATABASE CHECK OPTIONS"
.PP
The following options are available with the \fBcheckdb\fR subcommand:
.TP
\fB-P,--progress\fR
Displays a progress indicator.
.TP
\fB--check-only\fR
Behaves like normal, except that no changes are committed to the database.
.TP
\fB--dry-run\fR
This command is a synonym for \fB--check-only\fR.

.SH "SEE ALSO"
.nf
\fBREADME\fR
\fBhttp://github.com/jsbackus/bit_rot_detector/wiki\fR
.fi

.SH "COPYRIGHT"
Copyright \(co 2013 Jeff Backus <jeff.backus@gmail.com>
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "AUTHORS"

.nf
Jeff Backus <jeff.backus@gmail.com>
.fi
