#!/usr/bin/python

from __future__ import unicode_literals
import logging
import os
import stat
import hashlib
import argparse
import sqlite3
import operator
import time
import io
import sys
import datetime

###########
# Globals #
###########
table_names = { 'files': 'fp_files', 'dirs': 'fp_dirs', 
                'tmp_dirs' : 'tmp_dirs' }

version = 0
home_url = "https://github.com/jsbackus/simple_file_integrity_tool"

#############
# Functions #
#############
def parse_args():
    """Sets up the argparse object and attempts to parse the command-line.
    """
    
    # Create parser object
    parser = argparse.ArgumentParser(description=
                                     'Tool verify file integrity.' + os.linesep
                                     + "For more information: " + home_url)
    parser.add_argument('--version', action="version", 
                        version="%(prog)s version "+str(version) + 
                        " (c) 2013 Jeff Backus")
    parser.add_argument('-l', '--log', nargs='?', 
                        default='', help='log to file instead of console')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='only display warnings and errors')
    parser.add_argument('-d', '--debug', action='store_true',
                        help='display debugging information')
    parser.add_argument('--db', default='check_files.db',
                        help='Database that contains file fingerprint info.')

    subparsers = parser.add_subparsers(title='subcommands', dest='subcommand',
                                       description='valid subcommands',
                                       help='Subcommand Help')
    # Scan subparser
    scan_mode = subparsers.add_parser('scan', 
                                      help='Scans and checks the filesystem')

    scan_mode.add_argument('-p', '--prune', action='store_true',
                           help='Prunes directories and files from database ' +
                           'that no longer exist on the filesystem.')
    scan_mode.add_argument('-P', '--progress', action='store_true',
                           help='Displays progress meter.')
    scan_mode.add_argument('--dry-run', action='store_true',
                           help='prints commands to execute, but don\'t do ' +
                           'anything.')
    scan_mode.add_argument('-s', '--skip-recent', action='store_true',
                           help='When scanning, skips files in directories that'
                           + ' have been checked recently. See --expr.')
    scan_mode.add_argument('--expr', default=30, type=int,
                           help="Specifies how old 'recent' is, in days, when" +
                           " skipping recent files.")
    scan_mode.add_argument('-r', '--root', default='',
                           help='Specifies the root.')
    scan_mode.add_argument('target', nargs='+', 
                           help='Root of a directory tree to scan and check.')

    # Dupe files subparser
    dupe_files_mode = subparsers.add_parser('dupe_files', 
                                            help='Scans the database for ' +
                                            'duplicate files by fingerprint.')
    dupe_files_mode.add_argument('output', nargs='?', default='',
                                  help='Optional file to dump list of ' +
                                  'duplicates to.')

    # Dupe subtrees subparser
    dupe_trees_mode = subparsers.add_parser('dupe_trees', 
                                             help='Scans the database for ' +
                                             'duplicate directory subtrees.')
    dupe_trees_mode.add_argument('--nofilefp', action='store_true',
                                 help="Don't include file fingerprints in " +
                                 "directory fingerprints.")
    dupe_trees_mode.add_argument('--nofilename', action='store_true',
                                 help="Don't include file names in directory " +
                                 "fingerprints.")
    dupe_trees_mode.add_argument('--nosubdirfp', action='store_true',
                                 help="Don't include subdirectory " +
                                 "fingerprints in directory fingerprints.")
    dupe_trees_mode.add_argument('--nosubdirname', action='store_true',
                                 help="Don't include subdirectory names in " +
                                 "directory fingerprints.")
    dupe_trees_mode.add_argument('--nodirname', action='store_true',
                                 help="Don't include a directory's name in " +
                                 "its own fingerprint.")
    dupe_trees_mode.add_argument('output', nargs='?', default='',
                                  help='Optional file to dump list of ' +
                                  'duplicates to.')

    # Diff Root subparser
    diff_mode = subparsers.add_parser('diffroot', 
                                      help='Scans the database for ' +
                                      'duplicate directory subtrees.')
    diff_mode.add_argument('output', nargs='?', default='',
                           help='Optional file to dump list of ' +
                           'duplicates to.')
    diff_mode.add_argument('root_names', nargs=2, 
                           help='Names of roots/subtrees to check')

    # Check DB subparser
    checkdb_mode = subparsers.add_parser('checkdb', 
                                         help='Fingerprints the database in ' +
                                         'order to verify it.')
    checkdb_mode.add_argument('-P', '--progress', action='store_true',
                              help='Displays progress meter.')

    # list subparser
    list_mode = subparsers.add_parser('list',
                                      help='Displays database contents')
    list_mode.add_argument('target', nargs='*', default='',
                           help='Entry to list. Format: <root>/<path>')

    # delroot subparser
    delroot_mode = subparsers.add_parser('delroot',
                                      help='Removes roots and their contents ' +
                                         'from the database.')
    delroot_mode.add_argument('target', nargs='+', default='',
                           help='Root to remove.')

    # Create namespace from command-line
    return parser.parse_args()

def setup_logger(verbose_mode, debug_mode, filename=''):
    """Sets up the global logging object.
    """

    # Set up root logger
    rootLogger = logging.getLogger()
    rootLogger.setLevel(logging.DEBUG)

    # Set up formatter info
    formatter_str = '[%(asctime)s %(levelname)s] %(message)s'
    formatter_date = '%Y-%m-%d %I:%M:%S'

    formatter = logging.Formatter(formatter_str, formatter_date)

    # Set up file logger, if appropriate
    if 0 < len(filename):
        fh = logging.FileHandler(filename)
        
        # Determine log level. For files, assume INFO
        if debug_mode:
            fh.setLevel(logging.DEBUG)
        else:
            fh.setLevel(logging.INFO)

        # Set formatter
        fh.setFormatter(formatter)

        # Add to root logger
        rootLogger.addHandler(fh)

        # Log file-only messages
        logging.info('Logging started')

        if debug_mode:
            logging.info('Logging debug messages is enabled')
        
    # Set up console logger
    con = logging.StreamHandler()
    # Set formatter
    formatter = logging.Formatter('\r' + formatter_str, formatter_date)
    con.setFormatter(formatter)

    # Set level
    if debug_mode:
        con.setLevel(logging.DEBUG)
    elif verbose_mode:
        con.setLevel(logging.INFO)
    else:
        con.setLevel(logging.WARNING)

    # Add to root logger
    rootLogger.addHandler(con)

# \/ \/ Consider removing this function \/ \/
def tokenize_path(path):
    """Generator to tokenize a path via os.path.split. 
    Note: tokens will return in reverse order!
    """
    tmp_path = path
    while True:
        elms = os.split(tmp_path)
        if len(elms[1]) <= 0:
            break
        tmp_path = elms[0]
        yield elms[1]
# /\ /\ Consider removing this function /\ /\

# \/ \/ Consider removing this function \/ \/
def serialize_hash_of_lists( hash_of_lists ):
    """Generator to serialize a hash of lists. It goes through the keys of the
    hash in no particular order, returning the items of each list one at a time
    as a tuple.
    """
    keys_list = hash_of_lists.keys()
    cur_key = ""
    cur_idx = -1
    while True:
        if cur_idx < 0 or len(hash_of_lists[ cur_key ]) <= cur_idx:
            if 0 < len(keys_list):
                cur_key = keys_list.pop()
            else:
                break
            cur_idx = 0
        if cur_idx < len(hash_of_lists[ cur_key ]):
            tmp = (hash_of_lists[ cur_key ][ cur_idx ],)
#            logging.debug("Yielding %s", tmp)
            yield tmp
            cur_idx += 1
        else:
            break
# /\ /\ Consider removing this function /\ /\

def read_in_chunks(file_obj, chunk_size=1024*1024):
    """Generator to read data from the specified file in chunks.
    Default chunk size is 1M.
    """
    while True:
        data = file_obj.read(chunk_size)
        if not data:
            break
        yield data

def calc_fingerprint(filename, file_size=0):
    """Returns a string containing the SHA1 fingerprint of this file.
    """
    # Create a new SHA1 object and read from the specified file in chunks.
    result = hashlib.sha1()
    
    # Generate progress-friendly version of the filename
    if cmd_args.progress:
        bytes_read = 0
        last_line_len = 0
        prog_fn = os.path.basename(filename)
        if 21 < len(prog_fn):
            prog_fn = prog_fn[:9] + '...' + prog_fn[-9:]
        start_time = time.time()

    with open(filename, 'rb') as f:
        for read_data in read_in_chunks(f):
            result.update(read_data)

            if cmd_args.progress:
                bytes_read += len(read_data)
                avg_speed = time.time() - start_time

                if 0 < avg_speed:
                    avg_speed = bytes_read / avg_speed
                else:
                    avg_speed = "N/A"

                status_line = prog_fn + ': ' + str(bytes_read) + ' of '
                status_line += str(file_size) + ' bytes @ ' 
                if 1e6 < avg_speed:
                    status_line += '{:03.2f}'.format(avg_speed / 1e6) + 'MB/s'
                elif 1e3 < avg_speed:
                    status_line += '{:03.2f}'.format(avg_speed / 1e6) + 'KB/s'
                else:
                    status_line += '{:03.2f}'.format(avg_speed / 1e6) + 'B/s'

                # print new line
                sys.stdout.write('\r'+status_line + 
                                 (' ' * (last_line_len-len(status_line) + 1)))
                last_line_len = len(status_line)
                
    if cmd_args.progress:
        sys.stdout.write('\n')

    # Return fingerprint
    return result.hexdigest()
    
def process_file(node, filename, mode, file_db_dict, cursor):
    """Processes the specified file. This function is responsible for
    calculating the fingerprint of the file and comparing it against the
    database. If the fingerprints don't match, the modification times are
    compared.

    Returns a dict that can be used to update stats. 
    """

    # Concatenate path and filename
    fullname = os.path.join(node[0], filename)

    # Log the file
    logging.info('Processing file \'%s\'', fullname)
    
    # Generate fingerprint
    fp_cpu_time = time.clock()
    fp_real_time = time.time()
    fp = calc_fingerprint(fullname, mode.st_size)
    fp_cpu_time = time.clock() - fp_cpu_time
    fp_real_time = time.time() - fp_real_time
    logging.debug('File \'%s\' finished in %.4f seconds (%.4f CPU seconds)', 
                  fullname, fp_real_time, fp_cpu_time)

    # Update stats with throughput info
    ret_val = { "bytes" : mode.st_size, "time" : fp_real_time }

    # Attempt to access this file's entry in the DB dict. If we throw an
    # exception, we'll need to add the file to the database. If no exception
    # process the file.
    try:
        # Split out entries of file_rec to local variables to avoid confusion
        logging.debug('Entry: %s', file_db_dict[filename])
        db_id = file_db_dict[filename][0]
        db_mtime = file_db_dict[filename][1]
        db_fp = file_db_dict[filename][2]
        db_size = file_db_dict[filename][3]

        # Remove file from db dict to indicate that we've seen it.
        del(file_db_dict[filename])
        logging.debug("Marking file '" + fullname + "' as seen.")

        # Check file against database
        if db_fp != fp:
            # Fingerprints don't match...
            logging.debug('File \'' + fullname + '\' does not match ' +
                          'fingerprint in database')
                    
            # Compare modification times. If this file is newer, 
            # update database. Otherwise issue a warning.
            if float(db_mtime) < mode.st_mtime:
                logging.info('File \'' + fullname + '\' is newer than '
                             + 'database record. Updating...')

                update_file(db_id, fp, mode, cursor)

                # Return dict indicating update
                ret_val['updated'] = 1
                return ret_val
            else:
                logging.warning('File \'' + fullname + '\' does not ' +
                                'match fingerprint in database ' +
                                'and is not newer. File could be damaged!')

                # Return dict indicating problem
                ret_val['bad'] = 1
                return ret_val
        else:
            logging.debug('File \'' + fullname + '\' matches ' +
                          'fingerprint in database')

            # Double-check size to make sure we aren't fooling 
            # ourselves.
            if db_size != mode.st_size:
                logging.warning('File sizes do not match for ' +
                                'file \'' + fullname + 
                                '\'! File could be damaged!')
                # Return dict indicating problem
                ret_val['bad'] = 1
                return ret_val
            else:
                logging.debug('File \'' + fullname + 
                              '\' matches file size in database')
                # Return dict indicating file ok
                ret_val['good'] = 1
                return ret_val

    except KeyError:
        # File doesn't exist in database - add
        add_file(filename, fp, mode, node[1], cursor)

        # Return dict indicating addition
        ret_val['added'] = 1
        return ret_val

def get_root_from_db(cursor, rootdir):
    """Searches the database using the specified cursor object for the first
    record in the roots table with the same name. If no record exists, one is 
    added. Returns the tuple: (root dir, root id, last_checked)
    """

    ret_val = -1

    # Search the database for this root by name. If it doesn't exist, add it.
    cursor.execute("SELECT Path_ID, LastChecked FROM '" + table_names['dirs'] + 
                   "' WHERE Name=? AND Parent_ID=?", (rootdir,-1))
    row = cursor.fetchone()
    if row == None:
        # Doesn't exist - add
        cursor.execute("INSERT INTO '" + table_names['dirs'] + 
                       "'(Name,Parent_ID) VALUES(?,?)", 
                       (rootdir,-1))
        ret_val = (cursor.lastrowid, "")
        logging.debug('Root \'' + rootdir + '\' not in database. Added ' +
                      'with ID = ' + str(ret_val))
    else:
        ret_val = (row[0], row[1])
        logging.debug('Root \'' + rootdir + '\' found in database with ID = ' +
                      str(ret_val))

    # Return Root_ID for this root
    return ret_val

def get_dir_items_from_db(cursor, parent_id, check_files):
    """Searches the database using the specified cursor object for all items
    in the dirs and files tables with the specified Parent_ID.
    
    A dict with the following structure is returned:
    * 'dir_entries' = A dict of dir names => (Path_ID) of all dirs in db with
      the specified parent.
    * 'file_entries' = A dict of filenames => (File_ID, LastModified, FP, Size)
      of all files in db with the specified parent.
    """

    ret_val = { 'dir_entries': dict(), 'file_entries': dict() }

    # Search the database for all directories with the specified parent.
    cursor.execute("SELECT Path_ID, Name, LastChecked from '" + 
                   table_names['dirs'] + "' WHERE Parent_ID=?", (parent_id,))

    for entry in cursor.fetchall():
        dir_id = entry[0]
        dir_name = entry[1]
        last_checked = entry[2]
        logging.debug("Found dir '%s' (ID='%s') with parent '%s'.", 
                      dir_name, dir_id, parent_id)
        ret_val['dir_entries'][dir_name] = (dir_id, last_checked)

    # Search the database for all files with the specified parent, unless
    # we're skipping the files in this directory.
    if check_files:
        cursor.execute("SELECT File_ID, Name, LastModified, Fingerprint, Size" +
                       " from '" + table_names['files'] + 
                       "' WHERE Parent_ID=?", (parent_id,))

        for entry in cursor.fetchall():
            file_id = entry[0]
            file_name = entry[1]
            file_mtime = entry[2]
            file_fp = entry[3]
            file_size = entry[4]
            logging.debug("Found file '%s' (ID='%s') with parent '%s'.", 
                          file_name, file_id, parent_id)
            ret_val['file_entries'][file_name] = (file_id, file_mtime, file_fp, 
                                                  file_size)

    # Return entry list
    return ret_val

def add_file(filename, fp, mode, parent_id, cursor):
    """ Adds the specified file with the specified mode, fingerprint, and
    parent_id to the 'files' table. Returns the new entry's File_ID.
    """
    cursor.execute("INSERT INTO '" + table_names['files'] + 
                   "'(Name, Parent_ID, LastModified, " +
                   "Fingerprint," +
                   " Size) VALUES(?, ?, ?, ?, ?)", 
                   (filename, parent_id, mode.st_mtime, fp, mode.st_size))
    ret_val = cursor.lastrowid
    logging.debug("File '%s' with parent %s' added to database with ID = %s",
                  filename, parent_id, str(ret_val))

    return ret_val

def update_file(file_id, fp, mode, cursor):
    """ Updates the specified file with the specified mode, fingerprint, and
    parent_id to the 'files' table.
    """
    cursor.execute("UPDATE '" + table_names['files'] + 
                   "' SET LastModified=?, Fingerprint=?, Size=? WHERE " +
                   "File_ID=?", (mode.st_mtime, fp, mode.st_size, file_id))

def add_dir(path, parent_id, cursor):
    """Adds the specified path with specified parent_id to the 'dirs' table.
    Returns the new entry's Path_ID.
    """

    cursor.execute("INSERT INTO '" + table_names['dirs'] + 
                   "'(Name, Parent_ID) VALUES(?, ?)", 
                   (path, str(parent_id)))
    ret_val = (cursor.lastrowid, None)
    logging.debug('Directory \'' + path + '\' added with ID = ' + str(ret_val))
    return ret_val

def mark_dir_checked(dir_id, cursor):
    """Marks the specified directory as "recently seen".
    """

    tmp_now = datetime.datetime.now()
    cursor.execute("UPDATE '" + table_names['dirs'] + 
                   "' SET LastChecked=? WHERE Path_ID=?", (tmp_now, dir_id))
                                                           

def prune_files(path, file_data, cursor):
    """This routine is responsible for iterating over the list of files in the
    database but not on the filesystem and either removing them from the 
    database or simply alerting the user, depending on command-line arguments.
    Returns a tuple to be added to the files stats tuple.
    """
    
    if 0 < len(file_data):
        for item in file_data.keys():
            if ok_to_prune:
                cursor.execute("DELETE FROM '" + table_names['files'] + 
                               "' WHERE File_ID = ?",
                               (file_data[item][0],))
                logging.info("File '%s' pruned from directory '%s'.", item, 
                             path)
            else:
                logging.warning("File '%s' no longer exists in directory '%s'!",
                                item, path)
    return { 'missing' : len(file_data) }

def prune_dirs(path, dir_data, cursor):
    """This routine is responsible for iterating over the list of directories in
    the database but not on the filesystem and either removing them from the 
    database or simply alerting the user, depending on command-line arguments.
    Note that it is necessary to remove subdirectories and files!
    Returns a tuple of tuples that contain the updated stats: (files, dirs)
    """

    done = False
    ret_val = [ { 'missing' : 0}, { 'missing' : 0 } ]
    item_data = { 'file_entries': dict(), 'dir_entries': dir_data }

    # Build a queue like in crawl_tree of all directories to be pruned.
    dir_queue = []

    while not done:
        # Each round, append any directories in the database dict to the queue.
        for item in item_data['dir_entries'].keys():
            dir_queue.append( ( path, item, item_data['dir_entries'][item]) )
            
        # Prune any files
        ret_val[0] = add_dicts(ret_val[0], prune_files(path, item_data[ \
                    'file_entries'], cursor))
        
        if 0 < len(dir_queue):
            # Pop the next directory off of the stack
            node = dir_queue.pop()

            # Update path to refer to this item
            path = os.path.join(node[0], node[1])

            # Grab all entries for this directory from the database
            item_data = get_dir_items_from_db(cursor, node[2][0], True)

            # Delete this item from the database, if appropriate
            if ok_to_prune:
                cursor.execute("DELETE FROM '" + table_names['dirs'] + 
                               "' WHERE Path_ID = ?",
                               (node[2][0],))
                logging.info("Subdirectory '%s' pruned from directory '%s'.", 
                             node[1], node[0])
            else:
                logging.warning("Subdirectory '%s' no longer exists in " +
                                "directory '%s'!", node[1], node[0])

            ret_val[1]['missing'] += 1
        else:
            done = True

    return ret_val

def add_dicts(d1, d2):
    """Properly vector-adds the specified dicts-of-numbers and returns the 
    result.
    """
    ret_val = dict()
    for key in d1.keys():
        if d2.has_key( key ):
            ret_val[ key ] = d1[ key ] + d2[ key ]
        else:
            ret_val[ key ] = d1[ key ]

    for key in d1.keys():
        if not ret_val.has_key( key ):
            if d1.has_key( key ):
                ret_val[ key ] = d1[ key ] + d2[key]
            else:
                ret_val[ key ] = d2[ key ]

    return ret_val

def scan_target(target, db_conn):
    """Scans the specified root, checking all files and directories that
    belong to it.
    Returns 0 if successful or 1 if error.
    """

    # Get DB cursor object
    cursor = db_conn.cursor()

    # Attempt to resolve the 
    target_info = resolve_target(target, cursor)

    # If nothing returned, assume the specified target is a new root.
    if target_info == None:
        root_info = get_root_from_db(cursor, target)
        return crawl_tree(target, root_info[0], root_info[1], cursor)
    else:
        # Otherwise, start crawling in the specified subtree
        cursor.execute("SELECT LastChecked FROM '" + table_names['dirs'] + 
                       "' WHERE Path_ID=?", (target_info['dir_id'],))
        row = cursor.fetchone()
        return crawl_tree(target, target_info['dir_id'], row[0], cursor)
        
def crawl_tree(rootdir, dir_id, last_checked, cursor):
    """Crawls the specified directory, processing all files that it finds.
    Returns 0 if successful or 1 if error.
    """

    # Build timedelta object used to determine if entities have expired.
    expr_check = datetime.timedelta(cmd_args.expr)

    # Push root onto queue to start process
    dir_queue = [(rootdir, dir_id, last_checked)]

    # Order: (added, good, updated, bad, missing, skipped)
    file_stats = { 'added' : 0, 'good' : 0, 'updated' : 0, 'bad' : 0, 
                   'missing' : 0, 'skipped' : 0, 'bytes' : 0, 'time' : 0.0 }
    dir_stats = { 'added' : 0, 'good' : 0, 'updated' : 0, 'bad' : 0, 
                  'missing' : 0, 'skipped' : 0}

    error_flag = 0

    try:
        # Walk the filesystem
        while 0 < len(dir_queue):
            node = dir_queue.pop()

            # Log the directory that we are processing
            logging.info("Processing directory '%s'", node[0])
            logging.debug("%s", node)

            # Figure out if we're skipping the files in this directory
            check_files = True
            if cmd_args.skip_recent:
                if (node[2] != None) and (0 < len(str(node[2]))):
                    tmp_delta = datetime.datetime.now() - node[2]
                    if not (expr_check < tmp_delta):
                        check_files = False
                        logging.info("Skipping files in '%s' because it was " +
                                     "last checked %s days ago.", node[0], 
                                     tmp_delta.days)

            # Query the database
            db_cpu_time = time.clock()
            db_real_time = time.time()
            dir_db_data = get_dir_items_from_db(cursor, node[1], check_files)
            logging.debug("Dir '%s' DB fetched in %.4f seconds (%.4f CPU " +
                          "seconds)",
                          node[0], time.time() - db_real_time, 
                          time.clock() - db_cpu_time)

            ## Process directory contents
            for entry in os.listdir(node[0]):
                # Generate full path to entry
                entry_full_name = os.path.join(node[0], entry)

                # Grab entry filesystem stats
                try:
                    entry_stat = os.stat(entry_full_name)

                    if os.path.islink(entry_full_name):
                        # Entry is a symbolic link, which we ignore.
                        logging.info("Skipping symbolic link '%s'",
                                     entry_full_name)
                        if stat.S_ISREG(entry_stat.st_mode):
                            file_stats['skipped'] += 1
                        elif stat.S_ISDIR(entry_stat.st_mode):
                            dir_stats['skipped'] += 1
                    
                    elif stat.S_ISREG(entry_stat.st_mode):
                        # Entry is a regular file.
                        
                        # Process file and update stats, unless we're skipping
                        # files in this directory
                        if check_files:
                            file_stats = add_dicts(file_stats, 
                                                   process_file(node, entry, 
                                                                entry_stat, 
                                                                dir_db_data[ \
                                        'file_entries'],
                                                                cursor))
                            # Update number of bytes read
                            
                        else:
                            file_stats['skipped'] += 1
                        
                    elif stat.S_ISDIR(entry_stat.st_mode):
                        # Attempt to push directory onto stack using data from 
                        # db. If there is an error, assume that the directory is
                        # new. Add it to the DB then push it onto the stack.
                        try:
                            tmp_data = dir_db_data['dir_entries'][entry]
                            dir_queue.append( (entry_full_name, tmp_data[0],
                                               tmp_data[1]) )
                            
                            del(dir_db_data['dir_entries'][entry])
                            logging.debug('Marking directory \'' + 
                                          entry_full_name +
                                          '\' as seen.')
                            
                            # Update stats
                            dir_stats['good'] += 1
                        except KeyError:
                            # Item not in list. Add then append to queue.
                            tmp_data = add_dir(entry, node[1], cursor)
                            dir_queue.append( (entry_full_name, tmp_data[0],
                                               tmp_data[1]) )

                            # Update stats.
                            dir_stats['added'] += 1

                except OSError as e:
                    logging.warning("OSError({0}): {1}".format(e.errno, 
                                                               e.strerror) +
                                    " on file '" + entry_full_name + "'")

            file_stats = add_dicts(file_stats, prune_files(node[0], 
                                                           dir_db_data[ \
                        'file_entries'], cursor))
            tmp_stats = prune_dirs(node[0], dir_db_data['dir_entries'], cursor)
            file_stats = add_dicts(file_stats, tmp_stats[0])
            dir_stats = add_dicts(dir_stats, tmp_stats[1])

            # Mark this directory has recently checked, if appropriate
            if check_files:
                mark_dir_checked(node[1], cursor)

    except KeyboardInterrupt:
        error_flag = 1
        logging.error("Interrupt detected, aborting crawl and " +
                      "committing all changes.")
    
    # Commit
    db_conn.commit()

    # Print stats!
    action_names = ('added', 'good', 'updated', 'BAD', 'MISSING', 'skipped')
    logging.info('Finished processing root \'' + rootdir + '\': ')
    logging.info('    Files:')
    for action in action_names:
        logging.info('      %s: %s', action, file_stats[action.lower()])
    logging.info('    Directories:')
    for action in action_names:
        logging.info('      %s: %s', action, dir_stats[action.lower()])

    speed_info = str(file_stats['bytes']) + " bytes processed in "
    speed_info += '{:03.2f}'.format(file_stats['time'])
    speed_info += ' seconds for an average speed of '

    avg_speed = file_stats['bytes'] / file_stats['time']
    if 1e6 < avg_speed:
        speed_info += '{:03.2f}'.format(avg_speed / 1e6) + 'MB/s'
    elif 1e3 < avg_speed:
        speed_info += '{:03.2f}'.format(avg_speed / 1e6) + 'KB/s'
    else:
        speed_info += '{:03.2f}'.format(avg_speed / 1e6) + 'B/s'

    logging.info(speed_info)
                 

    # Return error code
    return error_flag

def open_db(db_url):
    """Function to open the specified SQLite database and return a Connection
    object to it. If the requisite table structure does not exist, it will be
    created.
    """

    # Connect to database
    conn = sqlite3.connect(database=db_url, 
                           detect_types=sqlite3.PARSE_DECLTYPES)

    # Look for fingerprints table
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    found = {'files': False, 'dirs': False }
    for table in cursor.fetchall():
        logging.debug("Found table '" + table[0] + "'")
        for fp_table in table_names:
            if (table[0] == table_names[fp_table]):
                logging.debug("Found " + fp_table + " fingerprint table '" + 
                              table[0] + "'.")
                found[fp_table] = True

    # If not found, create
    if not(found['files']):
        cursor.execute("CREATE TABLE '" + table_names['files'] + 
                       "'(File_ID INTEGER PRIMARY KEY AUTOINCREMENT, " +
                       "Name TEXT, Parent_ID INTEGER, " +
                       "LastModified TEXT, Fingerprint TEXT, Size INTEGER)")
        cursor.execute("CREATE INDEX file_parent_idx ON " + table_names['files']
                      + "(Parent_ID)")
        
    if not(found['dirs']):
        cursor.execute("CREATE TABLE '" + table_names['dirs'] + 
                       "'(Path_ID INTEGER PRIMARY KEY AUTOINCREMENT, " +
                       "Name TEXT, Parent_ID INT, LastChecked TIMESTAMP)")
        cursor.execute("CREATE INDEX dir_parent_idx ON " + table_names['dirs']
                      + "(Parent_ID)")
        
    return conn

def reconstruct_tree(cursor):
    """Iteratively fetches ancestores for all items in the tmp_dirs table until
    all ancestors have been retrieved. Then reconstructs the paths for each 
    entry, returning a dict of dicts: 
    * roots : <path_id> : <root_name>
    * dirs : <path_id> : (<full path sans root name>, root id)
    """
    
    ret_val = { "roots" : {}, "dirs" : {} }
    done = False
    first_pass = True
    while not done:
        logging.debug("Reconstructing tree: First Pass? %s, Row Count: %s", 
                      str(first_pass), str(cursor.rowcount))
        if first_pass or ( 0 < cursor.rowcount ):
            cursor.execute("INSERT INTO '" + table_names['tmp_dirs'] + 
                           "' (Path_ID,Parent_ID" +
                           ") SELECT Path_ID,Parent_ID FROM '" + 
                           table_names['dirs'] + "' WHERE Path_ID IN " +
                           "(SELECT Parent_ID FROM '" + 
                           table_names['tmp_dirs'] + "' WHERE Parent_ID NOT " +
                           "IN (SELECT Path_ID FROM '" + 
                           table_names['tmp_dirs'] + "'))")
            first_pass = False
        else:
            done = True

    # Now retrieve directory names and place into a hash of path_id -> name
    # so that we can rebuild path names.
    # Note: we're expecting parents to have a numerically smaller ID than
    # their children. This will hold true as long as parents are always 
    # added to the database before processing children.
    parent_map = dict()
    cursor.execute("SELECT Path_ID,Parent_ID,Name FROM '" + 
                   table_names['dirs'] +
                   "' WHERE Path_ID IN (SELECT Path_ID FROM '" +
                   table_names['tmp_dirs'] + "') ORDER BY Path_ID")
    
    dir_node_count = 0
    for entry in cursor.fetchall():
        if entry[1] < 0:
            # Root, so wrap it in brackets
            ret_val['roots'][ entry[0] ] = entry[2]
        else:
            # Check to see if this directory's parent is in the list.
            # If not, parent is a root, so check there.
            if(ret_val['dirs'].has_key( entry[1] )):
                parent_node = ret_val['dirs'][ entry[1] ]
                ret_val['dirs'][ entry[0] ] = (os.path.join( \
                        parent_node[0], entry[2] ), parent_node[1])
                dir_node_count += 1
            elif(ret_val['roots'].has_key( entry[1] )): 
                ret_val['dirs'][ entry[0] ] = (os.path.join( "", entry[2] ), 
                                               entry[1] )
                dir_node_count += 1
            else:
                logging.error("Parent %s for directory %s (%s) not in map!",
                              entry[1], entry[2], entry[0])
                                                  
            
    logging.info("Directory nodes processed: " + str(dir_node_count))
    
    return ret_val

def gen_db_url(tree_info, parent_id, item):
    """Generates a suitable string representation of the specified entry in the
    database using the reconstructed tree information from reconstruct_tree().
    """

    if tree_info['dirs'].has_key( parent_id ):
        root_id = tree_info['dirs'][ parent_id ][1]
        ret_val = '[' + tree_info['roots'][ root_id ] + ']'
        ret_val = os.path.join(ret_val, tree_info['dirs'][ parent_id ][0], 
                               item)
    else:
        ret_val = '[' + tree_info['roots'][ parent_id ] + ']'
        ret_val = os.path.join(ret_val, item)
        
    return ret_val

def create_tmp_dir_table(cursor):
    """Creates the temporary directory table
    """
    cursor.execute("CREATE TEMP TABLE '" + table_names['tmp_dirs'] + 
                   "' (Path_ID INTEGER " +
                   "PRIMARY KEY, Parent_ID INTEGER)")

def drop_tmp_dir_table(cursor):
    """Deletes the temporary dir table
    """
    cursor.execute("DROP TABLE '" + table_names['tmp_dirs'] + "'")

def check_dupe_files(db_conn):
    """Scans the database looking for duplicate files by fingerprint and prints
    results to STDOUT or optional output file.
    """

    # Dict of lists by fingerprint
    file_hash = dict()
    
    # Dict of directories by ID
    dir_hash = dict()

    # Count of duplicates
    count = 0
    
    # Get DB cursor object
    cursor = db_conn.cursor()

    # Create a temporary table containing all duplicate files
    cursor.execute("CREATE TEMP TABLE TMP_DUPES AS SELECT " +
                   "File_ID,Name,Fingerprint,Parent_ID FROM '" + 
                   table_names['files'] + "' WHERE " +
                   "Fingerprint IN (SELECT Fingerprint from '" + 
                   table_names['files'] + "' GROUP BY Fingerprint HAVING " +
                   "1<COUNT(*)) ORDER BY Fingerprint")

    # Select all duplicate files
    cursor.execute("SELECT * FROM TMP_DUPES")
    for entry in cursor.fetchall():
        count += 1
        try:
            # Attempt to append the current entry to the end of list for 
            # its fingerprint
            file_hash[entry[2]].append( (entry[0], entry[1], entry[3]) )
        except KeyError:
            # New entry
            file_hash[entry[2]] = [ (entry[0], entry[1], entry[3]) ]

    # Populate directory lookup table so that we can reconstruct each path.
    # We'll use a SQL to do the heavy lifting to avoid shipping data back and
    # forth.
    if 0 < count:
        # Create temp table
        create_tmp_dir_table(cursor)

        # First pass, direct parents from files temp table
        cursor.execute("INSERT INTO '" + table_names['tmp_dirs'] + 
                       "' (Path_ID,Parent_ID) " +
                       "SELECT Path_ID,Parent_ID FROM '" + table_names['dirs'] +
                       "' WHERE Path_ID IN (SELECT Parent_ID FROM TMP_DUPES " +
                       "GROUP BY Parent_ID)")

        # Now reconstruct tree
        tree_info = reconstruct_tree(cursor)

        ## Display results

        # Open dupes file, if specified
        fh = None
        if 0 < len(cmd_args.output):
            fh = io.open(cmd_args.output, 'wt')
        elif not cmd_args.verbose or (0 < len(cmd_args.log)):
            fh = io.open(sys.stdout.fileno(), 'wt')
        
        for fp in file_hash.keys():
            # Send to log
            logging.info(str(len(file_hash[fp])) + " files with Fingerprint 0x" 
                         + fp + ":")

            for entry in file_hash[fp]:
                path_name = gen_db_url( tree_info, entry[2], entry[1] )
                logging.info("    " + path_name + " (ID = " + str(entry[0]) + 
                             ")")

            # Send to file/STDOUT if appropriate
            if not (fh == None):
                fh.write(str(len(file_hash[fp])) + " files with Fingerprint 0x" 
                         + fp + ":" + os.linesep)

                for entry in file_hash[fp]:
                    path_name = gen_db_url( tree_info, entry[2], entry[1] )
                    logging.info("    " + path_name + " (ID = " + str(entry[0]) 
                             + ")")
                    fh.write("    " + path_name + os.linesep)

        if not (fh == None):
            fh.close()

    logging.info("Duplicates found: " + str(count))

def check_dupe_trees(db_conn):
    """Scans the database looking for duplicate subtrees and prints results
    to STDOUT or optional output file.
    """

    # Get DB cursor object
    cursor = db_conn.cursor()

    # Dict of directories by ID: { ID -> [ name, parent id, dir fp ]
    dirs_by_id = dict()

    # Dict of directories by parent: { parent id -> [ dir ids ] }
    dirs_by_parent = dict()

    # Dict of directories by fp: { dir fp -> [ dir ids ] }
    dirs_by_fp = dict()

    # Count of duplicates
    count = 0

    # dict of directories waiting to be fingerprinted: 
    # { dir fp -> [ child ids waiting for fp ] }
    waiting_for_fp = dict()

    # Algorithm:
    # 1. Start with all directories that do not have any child directories:
    #    a. Populate the "queue" of dirs waiting for fp with these directories.
    #    b. Add the parents of these dirs to the lists of dirs by parent.
    #    c. Add these dirs to the list of dirs by id.
    # 2. Iterate over the dirs waiting to be fingerprinted. For each dir:
    #    a. See if any of its children are in in the "queue" to be 
    #       fingerprinted. If so, skip this dir.
    #    b. Grab all files in this dir from the database.
    #    c. Generate the fingerprint for this directory:
    #       i. Add this directory's name to the cypher, if appropriate.
    #       ii. Sort child files list alphabetically.
    #       iii. Add file names (if applicable) and file fingerprints 
    #           (if applicable) to the cypher.
    #       iv. Sort list of child directories alphabetically
    #       v. Add dir names (if applicable) and dir fingerprints (if 
    #          applicable) to encoder.
    #       vi. Update entry in list of dirs by id.
    #       vii. Add fingerprint to list of fingerprints from this pass.
    #       vii. Remove from list of dirs waiting for fp.
    # 3. Iterate over list of fingerprints generated this pass. For each fp,
    #    check the number of entries with the same fp. If > 1:
    #    b. Grab parent dir information from database.
    #    c. Add parent dirs to list of dirs waiting for fp.
    #    d. Add parent dirs to list of dirs by id and dirs by parent.
    # 4. Repeat 2 and 3 until list of dirs waiting to be fingerprinted is empty.
    # 5. TO DO: Need to only remove subtrees of matching nodes...
    # 6. Reconstruct trees for all remaining entries and report results

    # Select all directories that don't have any child directories into
    # temporary table
    cursor.execute("SELECT Path_ID,Name,Parent_ID FROM '" +
                   table_names['dirs'] + "' WHERE Path_ID NOT" +
                   " IN (SELECT Parent_ID FROM '" + table_names['dirs'] + "')")

    for entry in cursor.fetchall():
        # For the sake of legibility, lets create some local copies of
        # what we retrieved from the database.
        dir_id = entry[0]
        dir_name = entry[1]
        dir_parent = entry[2]
        
        # Add to dict of dirs by id.
        dirs_by_id[ dir_id ] = [ dir_name, dir_parent, None ]

        # Add to dict of dirs by parent.
        if not dirs_by_parent.has_key( dir_parent ):
            dirs_by_parent[ dir_parent ] = [ dir_id ]
        else:
            dirs_by_parent[ dir_parent ].append( dir_id )

        # Add to "queue" of directories to be fingerprinted. Since this dir
        # doesn't have any children to fingerprint, don't create a list.
        waiting_for_fp[ dir_id ] = None

        # Add debug message
        logging.debug( "Adding leaf node '%s', ID=%s, Parent=%s" )
        
    while 0 < len(waiting_for_fp):
        for dir_id in waiting_for_fp.keys():
            # Make sure we haven't already removed this id from the list
            if not waiting_for_fp.has_key( dir_id ):
                break

            # Check children for any that still need to be fingerprinted.
            no_outstanding_children = True
            if not waiting_for_children == None:
                for child_id in waiting_for_children[ dir_id ]:
                    # See if the child is in the list to be fingerprinted.
                    if waiting_for_children[ dir_id ].has_key( child_id ):
                        no_outstanding_children = False
                        break;
                    else:
                        # If not, make sure its fingerprint actually exists.
                        # If so, remove it from this list and move on. If not,
                        # throw up an error.
                        if dirs_by_id[ child_id ][ 2 ] != None:
                            del(waiting_for_children[ dir_id ][ child_id ])
                        else:
                            logging.error("Child '%s' (%s) of dir id %s " +
                                          "prematurely removed from list!",
                                          dirs_by_id[ child_id ][0], child_id,
                                          dirs_by_id[ child_id ][1])

            # Pop out if this directory is still waiting on children
            if not no_outstanding_children:
                break
            
            # Start generating a fingerprint
            skip_files = cmd_args.nofilefp and cmd_args.nofilename
### TO DO            
    while not done:
        # Grab all files who's parent is represented in the temporary table
        if not skip_files:
            cols = "Parent_ID,Name"
            if not cmd_args.nofilefp:
                cols += ",Fingerprint"
            cursor.execute("SELECT " + cols + " FROM '" + 
                           table_names['files'] + "' WHERE Parent_ID" +
                           " IN (SELECT Path_ID FROM '" +
                           table_names['tmp_dirs'] + "')")
            tmp_file_list = dict()
            for entry in cursor.fetchall():
                logging.debug("Processing file entry: %s", entry)
                if cmd_args.nofilefp:
                    val = 1
                else:
                    val = entry[2]
                if not tmp_file_list.has_key( entry[0] ):
                    tmp_file_list[ entry[0] ] = dict()
                if not tmp_file_list[ entry[0] ].has_key( entry[1] ):
                    tmp_file_list[ entry[0] ][ entry[1] ] = val
        logging.debug("tmp_file_list: %s", tmp_file_list)

        # Grab info for all directories represented in the temporary table
        cursor.execute("SELECT Path_ID,Name,Parent_ID FROM '" + 
                       table_names['dirs'] + "' WHERE Path_ID IN (SELECT " +
                       "Path_ID FROM '" + table_names['tmp_dirs'] + "')")

        # For each item, generate a fingerprint and stuff into local data
        # structures.
        for entry in cursor.fetchall():
            logging.debug("Processing dir entry %s", entry)
            
            # For the sake of legibility, lets create some local copies of
            # what we retrieved from the database.
            dir_id = entry[0]
            dir_name = entry[1]
            dir_parent = entry[2]

            if not dirs_by_id.has_key( dir_id ):
                dir_fp = hashlib.sha1()

                # Add directory name to hash, if appropriate
                if not cmd_args.nodirname:
                    dir_fp.update( dir_name )
            
                # Sort all files associated with this directory then add, if
                # appropriate
                if not skip_files and tmp_file_list.has_key( dir_id ):
                    for name in sorted( tmp_file_list[ dir_id ].keys() ):
                        if not cmd_args.nofilename:
                            dir_fp.update( name )
                        if not cmd_args.nofilefp:
                            dir_fp.update( tmp_file_list[ dir_id ][ name ] )

                # Store cypher for later
                dirs_by_id[ dir_id ] = [ dir_name, dir_parent, dir_fp, None ]

                # Store in parent -> [ dir_ids ]
                if not dirs_by_parent.has_key( dir_parent ):
                    dirs_by_parent[ dir_parent ] = []
                dirs_by_parent[ dir_parent ].append( dir_id )

        # Replace contents of temporary table with parents of current entries.
        cursor.execute("INSERT INTO '" + table_names['tmp_dirs'] + 
                       "' (Path_ID,Parent_ID,Level) SELECT Path_ID,Parent_ID," +
                       str(level+1) + " FROM '" + table_names['dirs'] + 
                       "' WHERE Path_ID IN (SELECT Parent_ID FROM '" + 
                       table_names['tmp_dirs'] + "')")
        cursor.execute("DELETE FROM '" + table_names['tmp_dirs'] + 
                       "' WHERE Level=?", (level,))
        level += 1
        cursor.execute("SELECT COUNT(*) FROM '" + table_names['tmp_dirs'] + "'")
        num_rows = cursor.fetchone()[0]
        logging.debug("Rows added for level %s: %s", level, num_rows)
        done = (num_rows <= 0)

    # At this point, we should have partial IDs for all directories in the
    # database. This could become a problem for really large databases on
    # machines with limited RAM/swap. May need to offload more of the 
    # algorithm to SQLite...

    # Retrieve the list of all directories that do not have children from the
    # database. Iterate through this list completing their fingerprints and
    # add their parents to a queue of directories that need to have their
    # fingerprint completed. Also, add the completed fingerprints to the
    # dict of fp -> [ path_ids ]
    cursor.execute("SELECT Path_ID FROM '" + leaf_dirs_table + "'")
    dirs_by_fp = dict()
    for entry in cursor.fetchall():
        dir_id = entry[0]

        # Finalize, convert to hex, and store
        dir_fp = dirs_by_id[ dir_id ][ 2 ].hexdigest()
        dirs_by_id[ dir_id ][ 2 ] = None
        dirs_by_id[ dir_id ][ 3 ] = dir_fp
        logging.debug("Fingerprint for directory '%s' (%s) = '0x%s'", 
                      dirs_by_id[ dir_id ][ 0 ], dir_id, dir_fp)

        # Add to fp -> [ path_ids ] map
        if not dirs_by_fp.has_key( dir_fp ):
            dirs_by_fp[ dir_fp ] = []
        dirs_by_fp[ dir_fp ].append( dir_id )
        
        # Add parent to queue, unless this directory is a root.
        if 0 <= dirs_by_id[ dir_id ][ 1 ]:
            waiting_for_children.append( dirs_by_id[ dir_id ][ 1 ] )

    # Now, iterate through the queue finalizing fingerprints. First make
    # sure that all child directories have been finalized. Each time a 
    # directory is finalized, swap its parent's ID into the list. Once
    # the root has been reached, swap from the end of the list.
    done = (len(waiting_for_children) <= 0)
    idx = 0
    while not done:
        # Make sure idx is within range
        if len(waiting_for_children) <= idx:
            idx = 0
        
        dir_id = waiting_for_children[ idx ]
        dir_parent = dirs_by_id[ dir_id ][ 1 ]
        dir_fp = dirs_by_id[ dir_id ][ 2 ]

        # Update fingerprints with subdirectory information, if appropriate
        all_leafs_finished = True
        if dir_fp != None and (not cmd_args.nosubdirfp) and \
                (not cmd_args.nosubdirname):

            # Check children
            logging.debug("Checking children of directory %s (%s)", dir_id,
                          idx)
            leaf_idx = 0
            while all_leafs_finished and \
                    leaf_idx < len(dirs_by_parent[ dir_id ]):
                
                leaf_id = dirs_by_parent[ dir_id ][ leaf_idx ]
                if dirs_by_id[ leaf_id ][ 3 ] == None:
                    all_leafs_finished = False
                leaf_idx += 1
                    
            # If all children are finalized, build a list of leaf names, sort 
            # it, and update fingerprint
            if all_leafs_finished:
                leaf_list = dict()
                for leaf_id in dirs_by_parent[ dir_id ]:
                    leaf_list[ dirs_by_id[ leaf_id ][ 0 ] ] = leaf_id

                for name in sorted( leaf_list.keys() ):
                    if not cmd_args.nosubdirname:
                        dir_fp.update( name )
                    if not cmd_args.nosubdirfp:
                        dir_fp.update( dirs_by_id[ leaf_list[ name ] ][ 3 ])
        
        # If all leafs are finished:, finalize fingerprint and store, then
        # swap this directory out for its parent. Otherwise, move onto the
        # next item in the list.
        if all_leafs_finished:
            if dir_fp != None:
                # Finalize fingerprint, convert to hex, and store
                dir_fp = dir_fp.hexdigest()
                dirs_by_id[ dir_id ][ 2 ] = None
                dirs_by_id[ dir_id ][ 3 ] = dir_fp
                logging.debug("Fingerprint for directory '%s' (%s) = '0x%s'", 
                              dirs_by_id[ dir_id ][ 0 ], dir_id, dir_fp)

                # Add to fp -> [ path_ids ] map
                if not dirs_by_fp.has_key( dir_fp ):
                    dirs_by_fp[ dir_fp ] = []
                    dirs_by_fp[ dir_fp ].append( dir_id )
        
            # Check parent. If this is not a root, swap parent into this items
            # place.
            if 0 <= dir_parent:
                waiting_for_children[idx] = dir_parent
            else:
                # If this is a root, pop an item off the end and swap into this 
                # item's place, unless this item is the last item.
                dir_parent = waiting_for_children.pop()
                if idx < len(waiting_for_children):
                    waiting_for_children[idx] = dir_parent
        else:
            idx += 1

        # Check length of queue and stop if 
        done = (len(waiting_for_children) <= 0)

    # Last pass before reconstructing the tree: Step through list of 
    # fingerprints:
    # * remove any that correspond to only have one item
    # * remove any where all items have parents with the same fingerprint.
    for fp in dirs_by_fp.keys():
        if len(dirs_by_fp[ fp ]) < 2:
            del(dirs_by_fp[ fp ])
        else:
            tmp_id = dirs_by_fp[ fp ][ 0 ]
            parent_fp = dirs_by_id[ dirs_by_id[ tmp_id ][ 1 ] ][ 2 ]

            idx = 1
            done = False
            while not done:
                if len(dirs_by_fp[ fp ]) <= idx:
                    done = True
                else:
                    tmp_id = dirs_by_fp[ fp ][ idx ]
                    if dirs_by_id[ dirs_by_id[ tmp_id ][ 1 ]][ 2 ] != parent_fp:
                        done = True
                    else:
                        idx += 1
            # See if we searched the whole list
            if len(dirs_by_fp[ fp ]) <= idx:
                # Yep, so we can drop it.
                del(dirs_by_fp[ fp ])

    logging.debug("Number of matches: %s", len(dirs_by_fp))
                
    # Iterate through dirs_by_fp, adding all directories to the temporary table
    cursor.executemany("INSERT INTO '" + table_names['tmp_dirs'] + 
                       "' (Path_ID,Parent_ID) SELECT Path_ID,Parent_ID FROM '" +
                       table_names['dirs'] + "' WHERE Path_ID=?", 
                       serialize_hash_of_lists( dirs_by_fp ) )

    # Now reconstruct tree
    tree_info = reconstruct_tree(cursor)

    ## Display results
    cursor.execute("SELECT COUNT(*) FROM '" + table_names['tmp_dirs'] + "'")
    if 0 < cursor.fetchone()[0]:
        # Open dupes file, if specified
        fh = None
        if 0 < len(cmd_args.output):
            fh = io.open(cmd_args.output, 'wt')
        elif not cmd_args.verbose or (0 < len(cmd_args.log)):
            fh = io.open(sys.stdout.fileno(), 'wt')
        
        count = 0
        for fp in dirs_by_fp.keys():
            # Send to log
            logging.info(str(len(dirs_by_fp[fp])) + " dirs with Fingerprint 0x" 
                         + fp + ":")

            for entry in dirs_by_fp[fp]:
                tmp_info = dirs_by_id[ entry ]
                path_name = gen_db_url( tree_info, tmp_info[0], tmp_info[1])
                logging.info("    " + path_name + " (ID = " + str(entry) + 
                             ")")

            # Send to file/STDOUT if appropriate
            if not (fh == None):
                fh.write(str(len(dirs_by_fp[fp])) + " dirs with Fingerprint 0x" 
                         + fp + ":" + os.linesep)

                for entry in dirs_by_fp[fp]:
                    tmp_info = dirs_by_id[ entry ]
                    path_name = gen_db_url( tree_info, tmp_info[0], tmp_info[1])
                    fh.write("    " + path_name + os.linesep)

            count += 1
        if not (fh == None):
            fh.close()

    logging.info("Duplicates found: " + str(count))

def del_roots(db_conn):
    """Attempts to remove the specified root
    """

    file_stats = { 'missing' : 0 }
    dir_stats = { 'missing' : 0 }

    # Get DB cursor object
    cursor = db_conn.cursor()

    for target in cmd_args.target:
        # Remove any trailing OS separators and split into tokens
        target = target.rstrip(os.sep)

        # Check for root in database
        dir_id = get_root_from_db(cursor, target)[0]
        dir_db_data = get_dir_items_from_db(cursor, dir_id, True)
    
        # Delete tree
        tmp_stats = prune_dirs(target, dir_db_data['dir_entries'], cursor)
        file_stats = add_dicts(file_stats, tmp_stats[0])
        dir_stats = add_dicts(dir_stats, tmp_stats[1])

    # Commit
    db_conn.commit()

    # Print stats!
    logging.info("Finished deleting target(s) '%s': ", cmd_args.target)
    logging.info("    Files: %s", file_stats['missing'])
    logging.info('    Directories: %s', dir_stats['missing'])

def resolve_target(target, cursor):
    """Attempts to resolve the specified target into root name + subdir. Returns
    a dict containing the root/dir/file names and IDs. Nonappicable fields will 
    be None. If the root cannot be resolved, None is returned.
    """

    ret_val = None

    # Remove any trailing OS separators and split into tokens
    path_nodes = target.rstrip(os.sep).split(os.sep)

    # Step through all nodes but the last one, probing database. Bail if we
    # can't find one.
    parent_id = -1
    idx = 1
    tmp_root = path_nodes[0]
    while parent_id < 0:
        cursor.execute("SELECT Path_ID FROM '" + table_names['dirs'] + 
                       "' WHERE Parent_ID=? AND Name=?", (parent_id, 
                                                          tmp_root) )
        tmp_row = cursor.fetchone()
        if tmp_row == None:
            if idx < len(path_nodes):
                tmp_root = os.path.join(tmp_root, path_nodes[idx])
                idx += 1
            else:
                logging.debug("Can't find root for %s!", target)
                return ret_val
        else:
            parent_id = tmp_row[0]

    logging.debug("Found root '%s' in target '%s'", tmp_root, target)
    ret_val = {'root_name' : tmp_root, 'root_id' : parent_id, 'dir_name' : None,
               'dir_id' : None, 'file_name' : None, 'file_id' : None }

    for idx in xrange(idx, len(path_nodes)-1):
        cursor.execute("SELECT Path_ID FROM '" + table_names['dirs'] + 
                       "' WHERE Parent_ID=? AND Name=?", (parent_id, 
                                                          path_nodes[idx]) )
        tmp_row = cursor.fetchone()
        if tmp_row == None:
            logging.info("Can't find directory '%s' in root '%s'!", 
                          path_nodes[idx], tmp_root)
            return ret_val
        else:
            parent_id = tmp_row[0]

    # Check dir table for last node
    if idx < len(path_nodes):
        cursor.execute("SELECT Path_ID FROM '" + table_names['dirs'] + 
                       "' WHERE Parent_ID=? AND Name=?", (parent_id, 
                                                          path_nodes[-1]) )
        tmp_row = cursor.fetchone()

    # Return results
    if (tmp_row != None):
        # Found entry in directories table.
        ret_val['dir_name'] = path_nodes[-1]
        ret_val['dir_id'] = tmp_row[0]
        logging.debug("Found target directory '%s' (%s) in root '%s' (%s)", 
                      ret_val['dir_name'], ret_val['dir_id'], 
                      ret_val['root_name'], ret_val['root_id'])

    else:
        # Try the file table
        cursor.execute("SELECT File_ID FROM '" + table_names['files'] + 
                       "' WHERE Parent_ID=? AND Name Like ?", 
                       (parent_id, path_nodes[-1]) )
        tmp_row = cursor.fetchone()
        if (tmp_row != None):
            ret_val['dir_id'] = parent_id
            ret_val['file_name'] = path_nodes[-1]
            ret_val['file_id'] = tmp_row[0]
            logging.debug("Found target file '%s' (%s) in root '%s' (%s)", 
                          ret_val['file_name'], ret_val['file_id'], 
                          ret_val['root_name'], ret_val['root_id'])
            
        else:
            logging.info("Unable to locate target '%s'!", target)

    return ret_val

def list_db(db_conn, target):
    """Lists all items that have target has a parent or display info on file if
    target is a file.
    """

    # Get DB cursor object
    cursor = db_conn.cursor()

    # Try to locate the target
    target_info = resolve_target(target, cursor)

    if (target_info == None) or (target_info['dir_id'] == None):
        print target + " is not in database." + os.linesep
        return 0
        

    count = 0

    if (target_info['dir_name'] != None):
        # Retrieve all children
        parent_id = target_info['dir_id']
        print target + ":"
        # dirs
        cursor.execute("SELECT Name,Path_ID FROM '" + 
                       table_names['dirs'] + "' WHERE Parent_ID=?", 
                       (parent_id,) )
        for row in cursor.fetchall():
            print "    " + os.path.join(row[0],"") + " (" + str(row[1]) + ")"
            count += 1
        # files
        cursor.execute("SELECT Name,File_ID FROM '" + 
                       table_names['files'] + "' WHERE Parent_ID=?", 
                       (parent_id,) )
        for row in cursor.fetchall():
            print "    " + row[0] + " (" + str(row[1]) + ")"
            count += 1
    
    # Try the file table
    if (target_info['file_id'] != None):
        print "Files matching " + target + ":" + os.linesep

        headers = ("Name", "ID", "Last Modified", "Fingerprint", "Size")
        cursor.execute("SELECT Name,File_ID,LastModified,Fingerprint,Size " + 
                       "FROM '" + table_names['files'] + 
                       "' WHERE Parent_ID=? AND " +
                       "Name Like ?", 
                       (target_info['dir_id'], target_info['file_name']) )
        for row in cursor.fetchall():
            print row[0] + ":"
            for idx in xrange(1, len(headers)):
                print "    " + headers[idx] + ": " + str(row[idx])
            count += 1

    print os.linesep + str(count) + " entries listed." + os.linesep
    return count

def write_db_fp(sha1, filename):
    """Helper function to write the specified sha1 to the specified filename.
    """
    try:
        fh = io.open(filename, 'wt')
        payload = sha1 + os.linesep
        fh.write(unicode(payload))
        fh.close()
    except IOError as e:
        logging.error("IOError({0}): {1}".format(e.errno, e.strerror) +
                      " on file '" + filename + "'")


def check_db():
    """Calculates the fingerprint of the database and checks it against the
    fingerprint in a file with the same name + 'sha1' extension. In the event
    that the fingerprints do not match, the mod times of the two files are
    compared. If the db was modified after the fingerprint file, the database
    is assumed fine and the fingerprint file is updated.
    """

    # For convenience...
    fullname = cmd_args.db

    # Log the file
    logging.info("Fingerprinting database '%s'", fullname)
    
    # Generate fingerprint
    fp_cpu_time = time.clock()
    fp_real_time = time.time()
    db_stat = os.stat(fullname)
    fp = calc_fingerprint(fullname, db_stat.st_size)
    logging.debug("Database '%s' has fingerprint '0x%s'", fullname, fp)
    logging.debug("File '%s' finished in %.4f seconds (%.4f CPU seconds)", 
                  fullname, time.time() - fp_real_time, 
                  time.clock() - fp_cpu_time)

    # Generate fingerprint filename
    fp_file = fullname + ".sha1"

    # Check against fingerprint file
    try:
        # Attempt to open the file. If we can't, assume that we need to create
        # a new one.
        fh = io.open(fp_file, 'rt')

        last_fp = fh.readline().rstrip()
        logging.debug("Previous fingerprint = '0x%s'", last_fp)

        if fp != last_fp:
            logging.debug("Database fingerprint does not match previous " +
                          "fingerprint.")

            # Check modification times.
            fp_stat = os.stat(fp_file)
            if fp_stat.st_mtime < db_stat.st_mtime:
                # Database has been touched since last fingerprint. Update.
                logging.info("Database '" + fullname + "' newer than " +
                             "fingerprint file '" + fp_file + "'. Updating...")
                write_db_fp(fp, fp_file)
            else:
                # Looks like something squirrelly is going on. Alert user.
                logging.warning("Database '" + fullname + "' does not match " +
                                "fingerprint file '" + fp_file + 
                                "'. Database could be damaged!")

        else:
            logging.info("Database fingerprint matches previous fingerprint.")

    except IOError:
        logging.info("Unable to open fingerprint file '" + fp_file + 
                     "'. Generating a new one.")
        write_db_fp(fp, fp_file)

########
# Main #
########

# Start timer
cpu_start_time = time.clock()
real_start_time = time.time()

# Parse command-line arguments
cmd_args = parse_args()

# Set up logger
setup_logger(cmd_args.verbose,cmd_args.debug,cmd_args.log)
logging.debug('Command-line arguments: %s', vars(cmd_args))

ok_to_prune = False

try:
    if cmd_args.subcommand == 'scan':
        if cmd_args.prune:
            ok_to_prune = True
        # Open fingerprint database
        with open_db(cmd_args.db) as db_conn:
            # Scan each specified root.
            for target in cmd_args.target:
                if (scan_target(target, db_conn) != 0):
                    break
        if cmd_args.progress:
            sys.stdout.write('\r\n')

    elif cmd_args.subcommand == 'dupe_files':
        # Open fingerprint database
        with open_db(cmd_args.db) as db_conn:
            check_dupe_files(db_conn)
            
    elif cmd_args.subcommand == 'dupe_trees':
        # Open fingerprint database
            with open_db(cmd_args.db) as db_conn:
                check_dupe_trees(db_conn)

    elif cmd_args.subcommand == 'diffroot':
        print "\n\nWarning: Not supported yet!\n"
        # Open fingerprint database
        #    with open_db(cmd_args.db) as db_conn:
        #        diff_roots(db_conn)
        
    elif cmd_args.subcommand == 'list':
        # Open fingerprint database
        with open_db(cmd_args.db) as db_conn:
            for target in cmd_args.target:
                list_db(db_conn, target)
            
    if cmd_args.subcommand == 'delroot':
        ok_to_prune = True
        # Open fingerprint database
        with open_db(cmd_args.db) as db_conn:
            del_roots(db_conn)

    elif cmd_args.subcommand == 'checkdb':
        check_db()

except KeyboardInterrupt:
    # Catch here also, in case it was missed earlier.
    logging.error("Interrupt detected! Aborting")
    pass

# Fini!
logging.info('Finished. Total Run Time = %.4f seconds (%.4f CPU seconds)', 
             time.time() - real_start_time, time.clock() - cpu_start_time)
